spring:
  datasource:
    url: jdbc:postgresql://ec2-3-213-192-58.compute-1.amazonaws.com:5432/dakc80irsitdn7
    username: nuvkalnteozjei
    password: 310e9b44e58545ebc10e907eac269615276e0b239a4ff4b40e3410eafb3a70d8
    driverClassName: org.postgresql.Driver

  security:
    oauth2:
      client:
        registration:
          biztoi:
            client-id: 7o2r51udt31kp738eumcvkj7eg
            client-secret: 1674uobc1lvpio2v8n9qvifecljiimce9dga7drf9amrq55i8bs4
            client-name: biztoi
            provider: cognito
            scope: openid, email, profile, aws.cognito.signin.user.admin
            redirect-uri: http://localhost:8000/login/oauth2/code/cognito
            authorization-grant-type: authorization_code
        provider:
          cognito:
            authorization-uri: https://biztoi-app-dev.auth.ap-northeast-1.amazoncognito.com/oauth2/authorize
            token-uri: https://biztoi-app-dev.auth.ap-northeast-1.amazoncognito.com/oauth2/token
            user-info-uri: https://biztoi-app-dev.auth.ap-northeast-1.amazoncognito.com/oauth2/userInfo
            jwk-set-uri: https://cognito-idp.ap-northeast-1.amazonaws.com/ap-northeast-1_ccxqYNJs0/.well-known/jwks.json
            user-name-attribute: username

server:
  port: 8000

aws:
  accessKeyId: XXXXXXYYYY
  secretKey: AAAAAAAABBBBBBB

application:
  front-url: http://localhost:3000
  aws:
    profile: "cognito-admin"
    pool: "ap-northeast-1_ccxqYNJs0"
  rakuten:
    app-id: "1035252894012359396"
    genre-id: "001006"
    aff-id: "1a4c4098.1308e707.1a4c4099.4c2137b0"
