server:
  port: 8000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/biztoi
    username: biztoi
    password: biztoi
    driverClassName: org.postgresql.Driver

rakuten:
  app-id: "1035252894012359396"
